export const CLEAR_SELECTED_EMAIL_ID = 'CLEAR_SELECTED_EMAIL_ID';
export const CLEAR_SELECTED_EMAILS = 'CLEAR_SELECTED_EMAILS';
export const MARK_EMAILS_AS_DELETED = 'MARK_EMAILS_AS_DELETED';
export const MARK_EMAILS_AS_READ = 'MARK_EMAILS_AS_READ';
export const MARK_EMAILS_AS_UNREAD = 'MARK_EMAILS_AS_UNREAD';
export const SELECT_EMAIL_ID = 'SELECT_EMAIL_ID';
export const SELECT_EMAIL = 'SELECT_EMAIL';
