export const CLEAR_SELECTED_EMAIL_ID = 'CLEAR_SELECTED_EMAIL_ID';
export const CLEAR_SELECTED_EMAILS = 'CLEAR_SELECTED_EMAILS';
export const SELECT_EMAIL_ID = 'SELECT_EMAIL_ID';
export const SELECT_EMAIL = 'SELECT_EMAIL';
